import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { Alegreya_Sans } from 'next/font/google'

const alegreya = Alegreya_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-Alegreya_Sans',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`${alegreya.variable} font-alegreya`}>{children}</body>
    </html>
  )
}
